name: gedcom
description: Dart library to parse GEDCOM data from string input ported from
  popular Python library
version: 0.1.0
repository: https://github.com/orestesgaolin/gedcom-dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  collection: ^1.15.0
  meta: ^1.3.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.2
  coverage: ^1.0.2
